spring.application.name=primo-progetto

server.port=8081
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

app.nome = Academy App
app.versione = 1.0.0
app.messaggio = Bevenuto nella nostra applicazione!

spring.profiles.active=dev