CREATE DATABASE palestra_db;

CREATE TABLE SOCI
(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
cognome VARCHAR(50) NOT NULL,
email VARCHAR(100),
data_iscrizione DATE,
attivo INT DEFAULT 1
);

CREATE TABLE CORSI
(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
istruttore VARCHAR(100),
max_partecipanti INT,
livello VARCHAR(20)
);

CREATE TABLE ISCRIZIONI
(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
socio_id INTEGER,
corso_id INTEGER,
data_iscrizione DATE
);